In [1]:
import numpy as np
import pandas as pd

In [3]:
r = pd.read_csv("heheda.csv")
r

        Id  SalePrice
0     1461  11.714830
1     1462  11.992663
2     1463  12.122421
3     1464  12.120733
4     1465  12.247792
5     1466  12.107206
6     1467  12.069621
7     1468  12.088283
8     1469  12.178977
9     1470  11.751535
10    1471  12.214041
11    1472  11.516019
12    1473  11.472396
13    1474  11.926945
14    1475  11.834566
15    1476  12.830233
16    1477  12.407100
17    1478  12.679106
18    1479  12.460097
19    1480  13.020410
20    1481  12.704289
21    1482  12.228833
22    1483  12.123894
23    1484  12.028981
24    1485  12.048516
25    1486  12.200885
26    1487  12.772978
27    1488  12.434654
28    1489  12.196012
29    1490  12.270926
...    ...        ...
1429  2890  11.355852
1430  2891  11.958542
1431  2892  10.844769
1432  2893  11.237634
1433  2894  10.931631
1434  2895  12.606567
1435  2896  12.558505
1436  2897  12.200482
1437  2898  11.969664
1438  2899  12.303249
1439  2900  11.947680
1440  2901  12.268860
1441  2902  12.143449
1442  2903  12.742783
1443  2904  12.685183
1444  2905  11.705088
1445  2906  12.113646
1446  2907  11.612522
1447  2908  11.744188
1448  2909  12.002939
1449  2910  11.366291
1450  2911  11.381232
1451  2912  11.931113
1452  2913  11.402450
1453  2914  11.398988
1454  2915  11.398988
1455  2916  11.404500
1456  2917  11.931392
1457  2918  11.683242
1458  2919  12.271665

[1459 rows x 2 columns]

In [4]:
r["SalePrice"] =  np.expm1(r["SalePrice"])
r

        Id      SalePrice
0     1461  122372.062296
1     1462  161564.107894
2     1463  183949.376142
3     1464  183639.147309
4     1465  208519.411291
5     1466  181171.746213
6     1467  174488.770013
7     1468  177775.608897
8     1469  194652.569129
9     1470  126947.282677
10    1471  201599.033045
11    1472  100308.842701
12    1473   96027.122333
13    1474  151287.681501
14    1475  137937.908226
15    1476  373334.556871
16    1477  244530.759746
17    1478  320969.868451
18    1479  257839.696157
19    1480  451534.957002
20    1481  329155.749057
21    1482  204603.360638
22    1483  184220.495539
23    1484  167539.656335
24    1485  170844.667673
25    1486  198964.209557
26    1487  352559.599286
27    1488  251362.028523
28    1489  197996.863322
29    1490  213399.452816
...    ...            ...
1429  2890   85463.118546
1430  2891  156144.193928
1431  2892   51264.298186
1432  2893   75934.055345
1433  2894   55916.383974
1434  2895  298511.559938
1435  2896  284503.781012
1436  2897  198884.074650
1437  2898  157890.646811
1438  2899  220409.831750
1439  2900  154457.396032
1440  2901  212959.023407
1441  2902  187858.443168
1442  2903  342073.329744
1443  2904  322926.442150
1444  2905  121185.802060
1445  2906  182342.272920
1446  2907  110471.501869
1447  2908  126017.946728
1448  2909  163232.902303
1449  2910   86359.977829
1450  2911   87659.971487
1451  2912  151919.527423
1452  2913   89539.874090
1453  2914   89230.363015
1454  2915   89230.363015
1455  2916   89723.577954
1456  2917  151961.916792
1457  2918  118567.009448
1458  2919  213557.265756

[1459 rows x 2 columns]

In [5]:
r.to_csv("sub.csv")